spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: <your mail id>
    password: <smtp mail server password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true